"""Shared constants used across the Bone Importer addon."""

from mathutils import Vector


RESERVED_PALETTE_ROWS = 3
DEFAULT_PART_ROW_COUNT = 1000
DEFAULT_PREVIOUS_FRAME_ROW_OFFSET = 100000
DEFAULT_BUFFER_ROW_COUNT = 200000
GAME_TO_BLENDER_X_ROTATION_DEGREES = 90.0
DEFAULT_PROXY_BONE_DIRECTION = Vector((0.0, 0.0, 1.0))
FLOAT_COMPARISON_EPSILON = 1e-8
